### ISSUE TITLE
Add pagination to webpages for Harvard cases

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1104]
Alas, the star pagination doesn't show up on our current pages. Case.law has some decent code for this, sort of like:

```css
.page-label::before {
    display: inline-block;
    content: attr(data-label);
    position: absolute;
    left: 0;
    transform: translateX(-100%);
    padding-right: 1em;
    font-size: 1.2rem;
}
```

It's probably worth checking out, though I think before it'll work we'll need to run some sort of transform on the HTML we have to convert it into something more useful. Theirs seems to have a bunch of formatting ours lacks.
