### ISSUE TITLE
The judge-pics docker volume won't refresh

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1751]
So judge pages have a boolean that determines whether they have a picture. If they do, then we try to construct the URL to that judge's portrait using their name and sometimes birthday. That path to their portrait is then passed to the staticfiles.json manifest file, where it looks up the photo in S3 and serves it to the user. Simple enough, right? 

Except somebody named a file wrong. Instead of following the correct convention for poor judge Webb, they named the file:

```
webb-john-unknown.jpeg
```

It should have been either:

```
webb-john.jpeg (if we didn't know his birthday)
```

Or:

```
webb-john-2001-01-23.jpeg
```
If we did. 

So, anyway, we try to look up the correct URL in the staticfiles.jpeg file and that fails because it has that `-unknown` suffix. That's fine, but I can't figure out how to fix it. 

In the judge-pics repository, I easily fixed the file naming problem. We don't release judge-pics on pypi because it's too big for their system (300MB max), so instead we put it in a docker image that just has judge-pics installed and nothing much else. The entire dockerfile is:

```
FROM python:3.8-slim

RUN apt-get update --option "Acquire::Retries=3" --quiet=2 && \
    apt-get install \
        --no-install-recommends \
        --assume-yes \
        --quiet=2 \
        # So we can use Python-slim
        build-essential gcc python-dev git

RUN pip install git+https://github.com/freelawproject/judge-pics
```

Simple enough.

Then, we patch that docker file into our python installation inside our django image, using something like this in its compose file:

```
  cl-nginx:
    container_name: cl-nginx
    image: freelawproject/nginx:latest
    depends_on:
      - cl-python
    volumes:
      - cl-judge-pics:${PYTHON_PACKAGES}/judge_pics   <--- Magic part
      - ${CL_BASE_DIR:-../..}:/opt/courtlistener
      - ${CERT_HOME:-/etc/letsencrypt}:/etc/letsencrypt:ro
      - ${BULK_DIR:-/sata/}:/storage/
    ports:
      - "80:80"
      - "443:443"
```

That, too, is fine. It's fragile and finicky, but it works. 

# What I can't figure out

Here's the problem: I can't get the judge-pics image in our docker-compose file to update. I'm pretty much stumped, having spent several hours on it already. The docker image itself is updated and pushed, and I've verified that it's fine by logging into it and checking:

```
# Find the new image (that isn't running)
sudo docker container ls -a | grep judge

# Make a copy of the image we can mess with
sudo docker commit 35dd debug/judges

# Log into it and verify the contents
sudo docker run -it --rm --entrypoint sh debug/judges

# Nuke it again
sudo docker image rm debug/judges
```

Doing that, I can see the file with the corrected name inside the directory defined by PYTHON_PACKAGES (in .env): 

```
PYTHON_PACKAGES=/usr/local/lib/python3.8/site-packages/
```

Fine, fine, great. And I can pull the new docker image to the server and check that it's there. But I can't figure out how to update the actual volume in the compose file that is defined by the image. 

I'm stumped. It's a small thing and I've spent enough time on it, so the simple solution is to just mark judge-webb as not having a photo (that'll fix his page), but next time we add judge pics, I don't know how to deploy them. Docker!
