### ISSUE TITLE
Front end is sluggish; unclear why

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2774]
I'm not sure what's up with this, but I've noticed that the front end is quite sluggish and occasionally timing out. The biggest changes we're made lately are to gunicorn (see: #2640), so I'm going to start there, but this needs to be fixed.

**Comment by mlissner** [comment]
First thing I've noticed (Sentry COURTLISTENER-3TJ)  is that a few of our users are sending queries like:

http://www.courtlistener.com/api/rest/v3/docket-entries/?docket__id=&order_by=-date_created

And:

http://www.courtlistener.com/api/rest/v3/docket-entries/?fields=docket%2Crecap_documents%2Cdate_filed%2Centry_number%2Cdescription%2Cdate_modified%2Cdate_created%2Cdocument_type%2Cdocument_number%2Cattachment_number%2Cpacer_doc_id%2Cis_available%2Cfilepath_ia%2Cplain_text%2Cocr_status%2Cis_free_on_pacer%2Cresource_uri&format=json&order_by=-date_modified&page=23

I've contacted these people so hopefully that will help. 

I also noticed that I re-deployed the RT alert cronjob incorrectly, which created a lot of failing pods. That filled up the node, and the node couldn't create the pods it needed to. 

I think this might be fixed. I haven't noticed pages taking too long, but I'll keep an on it.

**Comment by ttys0dev** [comment]
> I'm not sure what's up with this, but I've noticed that the front end is quite sluggish and occasionally timing out.

Probably switching to ASGI will help a bit since it will use a more dynamic threadpool, I suspect we don't have enough threads enabled to handle the amount of concurrent requests we're seeing.

**Comment by mlissner** [comment]
Just to tinker with things a bit, I just tweaked our gunicorn k8s deployment to scale up at 60% instead of 70%:

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cl-python
  namespace: court-listener
spec:
  maxReplicas: 32
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cl-python
  targetCPUUtilizationPercentage: 60
```

We'll see if that helps ensure that we have enough pods.
