### ISSUE TITLE
Figure out access to the Elastic Cluster from the CourtListener Cluster

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2950]
We currently have two EKS clusters, Courtlistener and Elastic, each with its own DNS, load balancers, etc. While this is good for security and separation of concerns, it's not so good for accessing one from the other. 

We need to figure out how to access the Elastic Cluster from the CL one, so we can, ya know, make queries.

**Comment by mlissner** [comment]
There are a few ways to do this, but the simplest is to add a load balancer to the Elastic cluster. You can do that with:

```
apiVersion: v1
kind: Service
metadata:
  name: elastic-loadbalancer-vpc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: elastic-cluster
  ports:
    - name: https
      protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer
```

It's pretty much that easy. Once it's in place, you'll have a URL in the Service description (or the AWS console), and from the CL cluster, you can do:

```
curl -k https://xxxus-west-2.elb.amazonaws.com:9200 -u elastic:PASSWORD
```

That will return something like:

```
{
  "name" : "elastic-cluster-es-master-data-nodes-0",
  "cluster_name" : "elastic-cluster",
  "cluster_uuid" : "JbcvK3z0TES2C_T4h084sw",
  "version" : {
    "number" : "8.8.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "f8edfccba429b6477927a7c1ce1bc6729521305e",
    "build_date" : "2023-06-05T21:32:25.188464208Z",
    "build_snapshot" : false,
    "lucene_version" : "9.6.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

Great! And if you do it multiple times, you'll see the name of the node changing as it load balances the cluster. 

To get the password above, you'll use:

```
kubectl get secret elastic-cluster-es-elastic-user -o json  |  jq -r .data.elastic | base64 -d
```

Relates to #2867
