### ISSUE TITLE
Auto Update Juriscraper etc.

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3609]
@mlissner 

I looked into automating the update for juriscraper etc using dependabot but I think it's either difficult or unwieldy if you want to do it on our own schedule. 

I think the simplest and most elegant method would be to implement something like this.

```
name: PR update Free Law Project dependencies

on:
  workflow_dispatch:

jobs:
  update-juriscraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Update juriscraper
        run: |
          poetry update juriscraper reporters-db courts-db eyecite

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Update freelawproject dependencies
          title: Update freelawproject dependencies
          body: This PR updates the juriscraper package.
          branch: update-freelawproject-dependencies
```

this one would be triggered manually by selecting the action and running it - but we could easily set up a 
cross repository trigger to run this code after one of the pypi.yml actions was run.
