### ISSUE TITLE
Flaky Selenium Tests in Disclosure module

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/courtlistener#4958]
While working on PR #4931, Selenium tests for the disclosure module started failing unexpectedly. However, they passed when the action was rerun.

You can find the failing GitHub action run here:

https://github.com/freelawproject/courtlistener/actions/runs/12938299727/job/36088203841?pr=4931

We tried to use the screenshots generated at the end of the test run to help debug the issue. Unfortunately, the `DisclosureReactLoadTest` class overrides the tearDown method, which prevents screenshots from being captured for these specific tests.

**Comment by elisa-a-v** [comment]
I found another one:
[This PR](https://github.com/freelawproject/courtlistener/pull/4940) had all checks successful until `main` was merged into it, then we started getting failed Selenium tests.
- [first failed job](https://github.com/freelawproject/courtlistener/actions/runs/12940358566/job/36094512448?pr=4940), 6 errors including the ones in the failed job mentioned by @ERosendo in the description for this issue.
- [second failed job](https://github.com/freelawproject/courtlistener/actions/runs/12940358566/job/36096537222?pr=4940), 2 errors, same ones.

[Third attempt](https://github.com/freelawproject/courtlistener/actions/runs/12940358566/job/36097017455) was finally successful.

**Comment by ERosendo** [comment]
@mlissner I've been investigating the issue with our tests and noticed they started failing after we added the `cl-tailwind-reload` service to our `docker-compose` file. It seems the tests are failing because the Disclosure search component, a React component, is not loading properly. These react assets should be generated and updated by the `cl-webpack` service.

Here's a breakdown of both services for reference:

```
cl-webpack:
    container_name: cl-webpack
    working_dir: /opt/courtlistener/cl
    image: node:16
    volumes:
      - ${CL_BASE_DIR:-../../}:/opt/courtlistener
    env_file:
      - ../../.env.dev
    command: sh -c 'npm install && exec npx webpack --progress --watch --mode=development'
``` 

```
 cl-tailwind-reload:
    container_name: cl-tailwind-reload
    working_dir: /opt/courtlistener/cl
    image: node:16
    volumes:
      - ${CL_BASE_DIR:-../../}:/opt/courtlistener
    env_file:
      - ../../.env.dev
    command: sh -c 'npm install && exec npm run dev'
    tty: true
``` 

Both services run `npm install`, which might be causing conflicts because they share the same mounted volume. I suspect one installation might be overwriting files created by the other.

To address this, I tried tweaking `cl-tailwind-reload` to skip `npm install` and start only after `cl-webpack` finishes its installation. This seems to resolve the issue.

For reference, you can find the code to set a startup order between these services in this pull request: [#4959](https://github.com/freelawproject/courtlistener/pull/4959).
